name: paper-trail
services:
    paper-trail:
        stdin_open: true
        tty: true
        volumes:
            - $PWD:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - 3000:3000
        image: paper-trail
